# Generated by Django 5.0.2 on 2024-03-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='actionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('observation', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Action Histories',
            },
        ),
    ]
